"""Initial migrations

Revision ID: 7662169fa0e0
Revises:
Create Date: 2026-01-07 10:58:08.748292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7662169fa0e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='datasetstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generative_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_explainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('explainer_name', sa.String(), nullable=False),
    sa.Column('explanation_path', sa.String(), nullable=True),
    sa.Column('plot_path', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='explainerstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('local_explainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('explainer_name', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('explanation_path', sa.String(), nullable=True),
    sa.Column('plots_path', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('fit_parameters', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='explainerstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('exploration', sa.JSON(), nullable=True),
    sa.Column('train', sa.JSON(), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('installed_version', sa.String(), nullable=False),
    sa.Column('lastest_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'INSTALLED', 'ERROR', name='pluginstatus'), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('description_content_type', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('input_columns', sa.JSON(), nullable=False),
    sa.Column('output_columns', sa.JSON(), nullable=False),
    sa.Column('train_metrics', sa.JSON(), nullable=True),
    sa.Column('validation_metrics', sa.JSON(), nullable=True),
    sa.Column('test_metrics', sa.JSON(), nullable=True),
    sa.Column('splits', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generative_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='runstatus'), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('DashAI', 'Package', 'Task', 'Model', 'Metric', 'Dataloader', 'Converter', 'Explainer', name='plugintag'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('converter_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('converter', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='converterliststatus'), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explorer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('exploration_type', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('exploration_path', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='explorerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['generative_process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('split_indexes', sa.JSON(), nullable=True),
    sa.Column('optimizer_name', sa.String(), nullable=False),
    sa.Column('optimizer_parameters', sa.JSON(), nullable=False),
    sa.Column('plot_history_path', sa.String(), nullable=True),
    sa.Column('plot_slice_path', sa.String(), nullable=True),
    sa.Column('plot_contour_path', sa.String(), nullable=True),
    sa.Column('plot_importance_path', sa.String(), nullable=True),
    sa.Column('goal_metric', sa.String(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('run_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='runstatus'), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.Enum('TRAIN', 'VALIDATION', 'TEST', name='splitenum'), nullable=False),
    sa.Column('level', sa.Enum('LAST', 'TRIAL', 'STEP', 'EPOCH', name='levelenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_timestamp'), ['timestamp'], unique=False)

    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('huey_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('results_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'DELIVERED', 'STARTED', 'FINISHED', 'ERROR', name='predictionstatus'), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_timestamp'))
        batch_op.drop_index(batch_op.f('ix_metric_run_id'))

    op.drop_table('metric')
    op.drop_table('run')
    op.drop_table('process_data')
    op.drop_table('explorer')
    op.drop_table('converter_list')
    op.drop_table('tag')
    op.drop_table('parameter_history')
    op.drop_table('notebook')
    op.drop_table('generative_process')
    op.drop_table('experiment')
    op.drop_table('plugin')
    op.drop_table('pipeline')
    op.drop_table('local_explainer')
    op.drop_table('global_explainer')
    op.drop_table('generative_session')
    op.drop_table('dataset')
    # ### end Alembic commands ###
