"""Upload generative session endpoint

Revision ID: 98791b9df4f0
Revises: 57ff87150ae2
Create Date: 2026-03-02 10:36:29.764372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98791b9df4f0'
down_revision: Union[str, None] = '57ff87150ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generative_session', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_generative_session_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generative_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_generative_session_name'), type_='unique')

    # ### end Alembic commands ###
